## Loconotion Site Configuration File ##

# run
# cd loconotion
# python3 loconotion -v --clean --timeout 20 pencake/pencake.toml

# name of the folder that the site will be generated in
name = "PenCake"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotation will parse all sub-pages present on the page
page = "https://pencake.notion.site/fd2cab24d1404fb0a4cffb15972dc131"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Element Injection ##
  # defined as an array of tables [[site.inject]], followed by 'head' or 'body' to set 
  # the injection point, followed by name of the tag to inject
  # each key in the table maps to an atttribute in the tag
  # e.g. the following injects this tag in the <head>:
  #   <link href="favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/> 
  [[site.inject.head.link]]
  rel="icon" 
  sizes="40x40"
  type="image/png"
  href="/pencake/pencake-icon-40x40.png"

## Individual Page Settings ##
# the [pages] table defines override settings for individual pages, by defining 
# a sub-table named after the page url (or part of the url, but careful about
# not using a string that appears in multiple page urls)
[pages]
  # the following settings will only apply to this page: 
  #   https://www.notion.so/d2fa06f244e64f66880bb0491f58223d

  # en
  [pages.fd2cab24d1404fb0a4cffb15972dc131]
    slug = "pencake"
  [pages.5760bf385b20497eb6de76fa8af7bfe0]
    slug = "download"
  [pages.bcebb19a457440de95c8945990b2f973]
    slug = "faq"
  [pages.2cc5258780ec4c6b8e4106ccdbcc08a1]
    slug = "markdown"
  [pages.5e7ea7100c6247c5a318e28f47060bae]
    slug = "privacy"
  [pages.42403e51d9af4d2eae65655019460c8b]
    slug = "contact"

  # es
  [pages.adcb485311af4fc5a2b94b673fcfb0eb]
    slug = "pencake-es"
  [pages.bd7376a32fd24cf5a1cdcbd232275516]
    slug = "download-es"
  [pages.86e65c9410df4d4b8d1e8ecdd1e2d5c0]
    slug = "faq-es"
  [pages.dd05dfde366a403f971b7524f9431f18]
    slug = "markdown-es"
  [pages.a30371be18934db3b0f85ffca82fc83d]
    slug = "privacy-es"
  [pages.f3d7101c48e04561a94b4e363d22a81e]
    slug = "contact-es"

  # ptbr
  [pages.052e29952fe74df3b3035f1ee0cc416c]
    slug = "pencake-ptbr"
  [pages.e291c4a891714440817f1dc728ab14e1]
    slug = "download-ptbr"
  [pages.258bd8ed48744341aa3b31bcc94dab8b]
    slug = "faq-ptbr"
  [pages.70b874e19b5b49e0a93e8966335c8c85]
    slug = "markdown-ptbr"
  [pages.ce5e2c268f05486caccd1653425f796c]
    slug = "privacy-ptbr"
  [pages.3fadb375b84e42609a1cc030ac9ceefe]
    slug = "contact-ptbr"

  # zhcn
  [pages.0ac702b1d6eb4c54bc8987ec79a96564]
    slug = "pencake-zhcn"
  [pages.802cd615b72647cf9c65194a093e9684]
    slug = "download-zhcn"
  [pages.7fb5769e3b5b4c9ba9f2b27c9bb6039c]
    slug = "faq-zhcn"
  [pages.7b64360d942c42508fd8bd3a88cf2d6b]
    slug = "markdown-zhcn"
  [pages.5b908c632f3e4b1a835e9a542c6f0098]
    slug = "privacy-zhcn"
  [pages.c3479343fc8f45719a07184973ddaf47]
    slug = "contact-zhcn"

  # zhtw
  [pages.718da851ddbe448c8474b4a2d982e790]
    slug = "pencake-zhtw"
  [pages.b65041d43f1d499d93ae308f65b0d999]
    slug = "download-zhtw"
  [pages.3d9c47decd214b6cb1a85ee40435ef40]
    slug = "faq-zhtw"
  [pages.186572e33f724896bdbf1a8e34f3017d]
    slug = "markdown-zhtw"
  [pages.18010984565c4bdd89e6ad0f90968e7f]
    slug = "privacy-zhtw"
  [pages.f3b2e88a3b4c429e9f3d6da780b3bf36]
    slug = "contact-zhtw"

  # ja
  [pages.66987b5fa6d9425ca5a54e943f684c4b]
    slug = "pencake-ja"
  [pages.baf298b90c49406ebf0b1f96b49d2ccb]
    slug = "download-ja"
  [pages.970b7d0b6da040f6a4a3eeb96360b5e5]
    slug = "faq-ja"
  [pages.8365162e0b644285982ad35332413500]
    slug = "markdown-ja"
  [pages.d876855ede78401589511556bc8bd8ea]
    slug = "privacy-ja"
  [pages.bab11c63214f48198c231ab478c98a59]
    slug = "contact-ja"

  # ko
  [pages.6a65e719f1cb4f119fc6422103b5cab1]
    slug = "pencake-ko"
  [pages.8cc41c5df1aa45c984373b4631d30e31]
    slug = "download-ko"
  [pages.385c426f20bd4c9db9af3413dee104be]
    slug = "faq-ko"
  [pages.355a74a9ec954c868d57b4c16619e2cd]
    slug = "markdown-ko"
  [pages.544410e3b3ce446f813f34a19bdb6ad9]
    slug = "privacy-ko"
  [pages.88ba325c471942988b9ad1246e65b3c4]
    slug = "contact-ko"
